name: Run DuoXP

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'GitHub Token'
        required: true
      lessons:
        description: 'Number of lessons'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run DuoXP
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
          GITHUB_LESSONS: ${{ inputs.lessons }}
        run: |
          python DuoXP.py
